### PR TITLE
Allow fluent setters when configured on the MappingConfiguration

### PR DESCRIPTION
**Pull request by djarnis73**
Implementation attempt for #128, probably needs some tuning with regards to naming and documentation.

### CODE REVIEW

**Comment by schuettec** [comment]
Seems like an elegant solution to avoid the introspection problem. I will have a look - thank you!

**Comment by schuettec** [comment]
I created another branch to integrate your solution: #153

**Comment by schuettec** [comment]
Bad news....there is some kind of a cache working under the hood of class 'Properties' or the Java Bean introspection. Basically the "allowFluentSetter" cannot be switched on and off and vice-versa within the same vm.... The set-Method seems to be cached in the property descriptor.

I added a JUnit test in #153 to show the caching. @djarnis73 Would you like to help a little with the analysis?

**Comment by djarnis73** [comment]
Yeah, I made the `ChainedSetterTest.checkConfigurationOfChainedSetters` test pass by adding a `Introspector.flushCaches();` at the beginning of the test, so it looks like it is the Introspector cache that remembers the manually saved setter. 

Not really sure about the best workaround though:

- Call `ChainedSetterTest.checkConfigurationOfChainedSetters` before configuring each mapper. Probably quite expensive time wise and not an acceptable solution.
- Make it a globally static configuration option (at global feature you can enable but not disable again, I guess that would be acceptable for most use cases, but probably not all).
- Keep our own cache (like a static map) of the fluent setters and consult it for _false positives_.

**Comment by schuettec** [comment]
Okay this was definitely a caching problem. I solved it by creating a new instance of `PropertyDescriptor`. This bypasses the cache, because the instance is not visible to the introspection mechanism.

```
  static PropertyDescriptor checkForAndSetFluentWriteMethod(Class<?> inspectType, PropertyDescriptor pd) {
    String writeMethodName = pd.getName();
    writeMethodName = "set" + writeMethodName.substring(0, 1)
        .toUpperCase() + writeMethodName.substring(1);
    try {
      Method setMethod = inspectType.getDeclaredMethod(writeMethodName, pd.getPropertyType());
      if (Modifier.isPublic(setMethod.getModifiers())) {
        /*
         * Create a new PropertyDescriptor instance, because the one supplied here comes from the Java Introspector and
         * is cached VM-wide (?). Due to this caching, it is not possible to deactivate fluent setters for other mapper
         * instances. We have to create a new PropertyDescriptor to avoid this.
         */
        PropertyDescriptor clone = new PropertyDescriptor(pd.getName(), pd.getReadMethod(), setMethod);
        return clone;
      }
    } catch (NoSuchMethodException e) {
      // just ignore, the method does not have to exist
    } catch (IntrospectionException e) {
      throw new RuntimeException(e);
    }
    return pd;
  }
```
This fixed the problem :)

I will add a few test cases and the extension in the assertion part of ReMap and then we are good to go for the release :)

**Comment by schuettec** [comment]
Version 4.3.0 is released and on it's way to Maven Central :)

**Pull request merged**
