### PR TITLE
Replace java.beans with openbeans package

### PR DESCRIPTION
**Pull request by sebasira**
Propose solution for #134

I'm not familiar with the **pom.xml** I work with gradle and I need to add a repository so the **openbeans** will be found. 

As I don't want to mess things with pom.xml I need someone to tell/guide me on how and where to put this:

```xml
<repository>
    <id>redhat-ga-repository</id>
    <url>https://maven.repository.redhat.com/ga</url>
</repository>
```

I've done a small test in Android and it was working fine

### CODE REVIEW

**Comment by sebasira** [comment]
Travis is complaining about some file (`OmitTransformation.java`) not being well formatted. I don't know why. Maybe someone could give me a hand here. Thank you!

**Comment by schuettec** [comment]
Hi. Thanks for your contribution.

You can fix formatting by running
mvn formatter:format.

I had a quick look on what you did. It might be, that we have to fork ReMap
to build a separate Android version. Reason: ReMap provides a meta model of
the mapping. This model depends on java.beans/PropertyDescriptor. You
changed that and the change will not be backwards compatible.

Currently I try to find a solution for that.

Thx again for your work.

Sebastian M. Irazabal <notifications@github.com> schrieb am Sa., 17. Okt.
2020, 04:21:

**Comment by schuettec** [comment]
After a review of your changes, I'm afraid, that we cannot merge your PR. There are several reasons:

- Your PR changes the public API of ReMap and it's not backwards compatible.
- Your version relies heavily on the openbeans library. I can't find a stable and maintained project of this library.
- Currently I'm not able to build a CI pipeline that ensures Android compatibility.

You could build your own version of ReMap using your fork. Just rename groupId and artifactId in your fork to get out of the ReMap Maven namespace. Then build and install your own version to your local Maven repository. Run `mvn install` to do this. This way you can use ReMap with your changes in your project.

**Comment by sebasira** [comment]
Thank you @schuettec! I think I will stick to my fork for Android, then. Feel free to close this PR and / or the issue if you like. 

Thank you very much for your time!

**Pull request closed without merging**
