### PR TITLE
Make hamcrest a test scope dependency

### LINKED ISSUE #127: Hamcrest not in test scope
Hi

While inspecting the dependency tree in my local project I noticed that you have the hamcrest library as a transitive dependency, should it not be in test scope?

Best regards Jens

### PR DESCRIPTION
**Pull request by djarnis73**
Resolves #127

### CODE REVIEW

**Review by schuettec — APPROVED** [review]
Thanks for the PR.

**Comment by schuettec** [comment]
Somethings wrong with the travis build....I have to check that.

**Comment by djarnis73** [comment]
Yeah, not sure what went wrong, looks like it builds ok though: https://travis-ci.org/github/remondis-it/remap/builds/680119573 perhaps travis <-> github communication failed. Maybe it will retry after a while.

One thing I find strange though is that it will not build with at java8 sdk. It gives compile errors on some of the test cases. If built with a later sdk i.e. 11, it work fine.

**Comment by schuettec** [comment]
Yes seems to be a communication problem.

The problem with building on jdk8 goes down to a java bug in conjunction with generics :-/
But building with a later version is always a good workaround :)

**Comment by schuettec** [comment]
Yippie release 4.2.4 is building :)

**Pull request merged**
